/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Represents a positive or negative citation with its literal quote and journalism analysis.
export interface QuoteAnalysis {
  quote: string;
  analysis: string;
}

// Represents the segmented analysis for a single political actor or entity.
export interface EntityAnalysis {
  mentions: string; // Summary of general mentions or dynamic themes
  positives: QuoteAnalysis[];
  negatives: QuoteAnalysis[];
}

// Map of the required Argentine political entities to analyze.
export interface PoliticalAnalysis {
  axel_kicillof: EntityAnalysis;
  peronismo: EntityAnalysis;
  cristina_kirchner: EntityAnalysis;
  la_campora: EntityAnalysis;
  maximo_kirchner: EntityAnalysis;
}

// Structured results generated by the Senior Journalist AI.
export interface EconomicAnalysis {
  pbaEconomy: {
    summary: string;
    quotes: { quote: string; analysis: string }[];
  };
  nationalEconomy: {
    summary: string;
    quotes: { quote: string; analysis: string }[];
  };
}

export interface AnalysisResult {
  transcription: string; // Full verbatim transcript
  summary: string;       // Deep journalistic summary
  keyPoints: string[];   // Critical key take-aways
  relevantQuotes: {      // Most relevant overall quotes
    quote: string;
    context: string;
  }[];
  politicalAnalysis: PoliticalAnalysis;
  economicAnalysis?: EconomicAnalysis; // Highlight of economic factors at BA Province level and National Argentina level
}

// Item saved in the user's local history logs.
export interface JournalHistoryItem {
  id: string;
  title: string;
  type: "audio" | "text" | "audio_url";
  fileName?: string;
  fileSize?: string;
  pastedTextSnippet?: string;
  timestamp: string;
  result: AnalysisResult;
}
